# Generated by Django 3.2.16 on 2023-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_heart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadb',
            name='now_time2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
