# Generated by Django 3.2.16 on 2023-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_heart', '0002_datadb_now_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadb',
            name='now_time',
        ),
        migrations.AddField(
            model_name='datadb',
            name='send_time',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
