# Generated by Django 3.2.16 on 2023-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_heart', '0003_auto_20230204_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='cpu_ratio',
            field=models.FloatField(default='none'),
        ),
        migrations.AlterField(
            model_name='datadb',
            name='memory_ratio',
            field=models.FloatField(default='none'),
        ),
    ]
